apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ab
    spec:
      containers:
        - name: train-schedule
          image: loup21991/hellodocker
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
  selector:
    matchLabels:
      app: ab

